Event-name: BBQ
Date: 1 July 2022
Time: 11h00 - 16h00
Location: 1600 Pennsylvanie Avenue NW, Washington, DC
Description: Come when you please!
Host-name: Abraham Lincoln
Contact: awesome@person.org
RSVP-start: 2022-04-01T12:00:00-05:00
RSVP-end: 2022-06-01T12:00:00-05:00