Event-name: Épluchette
Date: 13 June 2022
Time: 11h00 - 16h00
Location: 307 Sutherland Drive, Kingston ON, K7K 5Y6
Description: Come when you please, shuck your corn, toss it in the pot and eat!
Host-name: Sébastien Généreux
Contact: genereux@fidei.email